/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "half_adder.v:1.1-6.10" *)
module half_adder(a, b, sum, cout);
  (* src = "half_adder.v:2.7-2.8" *)
  input a;
  wire a;
  (* src = "half_adder.v:2.10-2.11" *)
  input b;
  wire b;
  (* src = "half_adder.v:3.8-3.11" *)
  output sum;
  wire sum;
  (* src = "half_adder.v:3.13-3.17" *)
  output cout;
  wire cout;
  AND2X1 _0_ (
    .A(a),
    .B(b),
    .Y(cout)
  );
  XOR2X1 _1_ (
    .A(a),
    .B(b),
    .Y(sum)
  );
endmodule
